name: basic_input
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:
  polymer: ">=0.11.0 <0.12.0"
  logging: ">=0.9.0 <0.10.0"
  collection: ">=0.9.0 < 0.10.0"

# custom <basic_input dependencies>

  intl: ">=0.9.0 < 0.10.0"

# end <basic_input dependencies>

dev_dependencies:
  unittest: ">=0.11.0"
  browser: "any"

# custom <basic_input dev dependencies>
# end <basic_input dev dependencies>

transformers:

# custom <basic_input transformers>

  - polymer:
      entry_points:
        - web/examples/basic_input/basic_input.html

# end <basic_input transformers>

