name: mortgage_calculator
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:
  polymer: ">=0.11.0 <0.12.0"
  logging: ">=0.9.0 <0.10.0"
  collection: ">=0.9.0 < 0.10.0"

# custom <mortgage_calculator dependencies>

  intl: ">=0.9.0 < 0.10.0"

  basic_input:
    path: ../basic_input

# end <mortgage_calculator dependencies>

dev_dependencies:
  unittest: ">=0.11.0"
  browser: "any"

# custom <mortgage_calculator dev dependencies>

  ebisu: ">=0.0.9"

# end <mortgage_calculator dev dependencies>

transformers:

# custom <mortgage_calculator transformers>

  - polymer:
      entry_points:
        - web/examples/mortgage_calculator/mortgage_calculator.html

# end <mortgage_calculator transformers>

